name: tfm_shipmen_label_reader
description: TFM Shipments label reader app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bottom_bar_with_sheet: ^2.4.0
  flutter_spinkit: ^5.2.0
  dropdown_search: ^5.0.6
  http: 1.1.2
  fluttertoast: ^8.2.2
  flutter_svprogresshud: ^1.0.0
  decimal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/